from django.db import models

# Create your models here.
class Mlmodel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    Time = models.IntegerField(default=0)
    V1 = models.DecimalField(max_digits=65,decimal_places=16)
    V2 = models.DecimalField(max_digits=65,decimal_places=16)
    V3 = models.DecimalField(max_digits=65,decimal_places=16)
    V4 = models.DecimalField(max_digits=65,decimal_places=16)
    V5 = models.DecimalField(max_digits=65,decimal_places=16)
    V6 = models.DecimalField(max_digits=65,decimal_places=16)
    V7 = models.DecimalField(max_digits=65,decimal_places=16)
    V8 = models.DecimalField(max_digits=65,decimal_places=16)
    V9 = models.DecimalField(max_digits=65,decimal_places=16)
    V10 = models.DecimalField(max_digits=65,decimal_places=16)
    V11 = models.DecimalField(max_digits=65,decimal_places=16)
    V12 = models.DecimalField(max_digits=65,decimal_places=16)
    V13 = models.DecimalField(max_digits=65,decimal_places=16)
    V14 = models.DecimalField(max_digits=65,decimal_places=16)
    V15 = models.DecimalField(max_digits=65,decimal_places=16)
    V16 = models.DecimalField(max_digits=65,decimal_places=16)
    V17 = models.DecimalField(max_digits=65,decimal_places=16)
    V18 = models.DecimalField(max_digits=65,decimal_places=16)
    V19 = models.DecimalField(max_digits=65,decimal_places=16)
    V20 = models.DecimalField(max_digits=65,decimal_places=16)
    V21 = models.DecimalField(max_digits=65,decimal_places=16)
    V22 = models.DecimalField(max_digits=65,decimal_places=16)
    V23 = models.DecimalField(max_digits=65,decimal_places=16)
    V24 = models.DecimalField(max_digits=65,decimal_places=16)
    V25 = models.DecimalField(max_digits=65,decimal_places=16)
    V26 = models.DecimalField(max_digits=65,decimal_places=16)
    V27 = models.DecimalField(max_digits=65,decimal_places=16)
    V28 = models.DecimalField(max_digits=65,decimal_places=16)
    Amount = models.IntegerField(default=0)
    owner = models.ForeignKey('auth.User', related_name='mlmodels', on_delete=models.CASCADE)
    

    def __str__(self):
        return (str(self.owner) + str(self.created))
    class Meta:
        ordering = ['created']
   
   
    def save(self, *args, **kwargs):
        Time = kwargs.get('Time', 0)    
        V1 = kwargs.get('V1', 0)
        V2 = kwargs.get('V2', 0)
        V3 = kwargs.get('V3', 0)
        V4 = kwargs.get('V4', 0)
        V5 = kwargs.get('V5', 0)
        V6 = kwargs.get('V6', 0)
        V7 = kwargs.get('V7', 0)
        V8 = kwargs.get('V8', 0)
        V9 = kwargs.get('V9', 0)
        V10 = kwargs.get('V10', 0)
        V11 = kwargs.get('V11', 0)
        V12 = kwargs.get('V12', 0)
        V13 = kwargs.get('V13', 0)
        V14 = kwargs.get('V14', 0)
        V15 = kwargs.get('V15', 0)
        V16 = kwargs.get('V16', 0)
        V17 = kwargs.get('V17', 0)
        V18 = kwargs.get('V18', 0)
        V19 = kwargs.get('V19', 0)
        V20 = kwargs.get('V20', 0)
        V21 = kwargs.get('V21', 0)
        V22 = kwargs.get('V22', 0)
        V23 = kwargs.get('V23', 0)
        V24 = kwargs.get('V24', 0)
        V25 = kwargs.get('V25', 0)
        V26 = kwargs.get('V26', 0)
        V27 = kwargs.get('V27', 0)
        V28 = kwargs.get('V28', 0)
        Amount = kwargs.get('Amount', 0)
        owner = kwargs.get('owner', 0)
        super(Mlmodel, self).save(*args, **kwargs)
    